[package]
authors = ["Byron Wasti"]
categories = [
    "embedded",
    "no-std",
]
description = ""
keywords = []
license = "MIT OR Apache-2.0"
name = "prusto-watch"
repository = ""
version = "0.1.0"

[dependencies]
cortex-m = "0.4"
cortex-m-rtfm = "0.3"
cortex-m-semihosting = "0.2.0"
embedded-hal = "0.1.0"
nb = "0.1.1"
stm32f30x-hal = "0.1.1"

[dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.12"

[dependencies.stm32f30x]
features = ["rt"]
version = "0.6"
[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
debug = true
lto = true
