[package]
authors = ["Byron Wasti"]
categories = [
    "embedded",
    "no-std",
]
description = ""
keywords = []
license = "MIT OR Apache-2.0"
name = "open-watch"
repository = ""
version = "0.1.0"

[dependencies]
cortex-m = "0.3.1"
cortex-m-rtfm = "0.2.2"
cortex-m-semihosting = "0.2.0"

[dependencies.stm32f30x]
features = ["rt"]
version = "0.5.1"
#path = "../stm32f303"

[dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.8"

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
debug = true
lto = true
