[package]
authors = ["Byron Wasti <byron.wasti@gmail.com>"]
name = "stm32f303"
version = "0.1.0"

[dependencies]
bare-metal = "0.1.1"
cortex-m = "0.3.1"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.3.3"

[features]
rt = ["cortex-m-rt"]
